# $FreeBSD$

PORTNAME=	pructl
PORTVERSION=	g20180830
#PORTREVISION=	0
CATEGORIES=	devel

USE_GITHUB=     yes
GH_ACCOUNT=     mstuehn
GH_PROJECT=	pructl
GH_TAGNAME=	6b66250

MAINTAINER=	freebsd@justmail.de
COMMENT=	Utilities to interface with PRUs

LICENSE=	BSD2CLAUSE

LIB_DEPENDS=	libpru.so:devel/libpru

USES=		cmake libedit

.include <bsd.port.mk>
