#!/bin/sh

SYSCTL_VAR="hw.snd.latency"
SYSCTL_VAL=2
SYSCTL_CONF=sysctl.conf

OVERLAY_VAR="fdt_overlays"
OVERLAY_VAL="ti_pruss.dtbo"
OVERLAY_CONF="loader.conf"

set_latency()
{
    if [ ! -f ${SYSCTL_CONF} ]; then
        echo ${SYSCTL_VAR}="${SYSCTL_VAL}"
    elif sed -I.bak "s/${SYSCTL_VAR}=\"*[0-9]*\"*/${SYSCTL_VAR}=\"${SYSCTL_VAL}\"/" ${SYSCTL_CONF} ; then
        rm ${SYSCTL_CONF}.bak
    else
        echo "Error during setting ${SYSCTL_VAR}"
    fi
}

add_overlay()
{
    if [ ! -f ${OVERLAY_CONF} ]; then
        echo ${OVERLAY_VAR}="${OVERLAY_VAL}"
    elif sed -I.bak "/^${OVERLAY_VAR}=\"[a-zA-Z0-9]*/s/\"$/,${OVERLAY_VAL}\"/" ${OVERLAY_CONF} ; then
        rm ${OVERLAY_CONF}.bak
    else
        echo "Error during setting ${OVERLAY_VAR}"
    fi
}

remove_overlay()
{

    # TODO: does not handle leading commata
    if sed -I.bak "/^${OVERLAY_VAR}=\"[a-zA-Z0-9]*/s/,*${OVERLAY_VAL}//g" ${OVERLAY_CONF} ; then
        rm ${OVERLAY_CONF}.bak
    else
        echo "Error during ressettin ${OVERLAY_VAR}"
    fi
}

case $2 in
POST-INSTALL)
        sysrc doorbell_enable=yes
        set_latency
        add_overlay
        exit 0
        ;;
esac

