#!/bin/sh

SYSCTL_VAR="hw.snd.latency"
SYSCTL_VAL=2
SYSCTL_CONF="/etc/sysctl.conf"

OVERLAY_VAR="fdt_overlays"
OVERLAY_VAL="ti_pruss.dtbo"
OVERLAY_CONF="/boot/loader.conf"

set_latency()
{
    if [ ! -f ${SYSCTL_CONF} ] || [ "$(grep -c ^${SYSCTL_VAR} ${SYSCTL_CONF})" -eq "0" ]; then
        echo ${SYSCTL_VAR}="${SYSCTL_VAL}" >> ${SYSCTL_CONF}
    elif sed -I.bak "s/${SYSCTL_VAR}=\"*[0-9]*\"*/${SYSCTL_VAR}=\"${SYSCTL_VAL}\"/" ${SYSCTL_CONF} ; then
        rm ${SYSCTL_CONF}.bak
    else
        echo "Error during setting ${SYSCTL_VAR}"
    fi
}

add_overlay()
{
    if [ ! -f ${OVERLAY_CONF} ]; then
        echo ${OVERLAY_VAR}=\"${OVERLAY_VAL}\" >> ${OVERLAY_CONF}
    elif sed -I.bak "/^${OVERLAY_VAR}=\"[a-zA-Z0-9]*/s/\"$/,${OVERLAY_VAL}\"/" ${OVERLAY_CONF} ; then
        rm ${OVERLAY_CONF}.bak
    else
        echo "Error during setting ${OVERLAY_VAR}"
    fi
}

case $2 in
POST-INSTALL)
        sysrc doorbell_enable=yes
        set_latency
        add_overlay
        exit 0
        ;;
esac

